# Generated by Django 5.2 on 2025-05-10 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swag',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='Rating from 1 to 5 stars (half-star increments allowed)', max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
