# Generated by Django 5.2 on 2025-05-11 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swags', '0002_alter_swag_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swag',
            name='rating',
            field=models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
