# Generated by Django 5.2 on 2025-05-14 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swags', '0004_swagcomment_swagrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='swag',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year of the conference', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
